### ISSUE TITLE
Open Request and Response for public use

### ISSUE THREAD

**Issue by toby3d** [toby3d/telegraph#4]
Should I open Request method with the Response structure for public use? For all time of existence API, it seems, there are no preconditions for that it was necessary to do something by hands.

**Comment by Daniel-M** [comment]
Can you elaborate more please?

**Comment by toby3d** [comment]
@Daniel-M All methods pass through the `request()` function, which, usually in many packages, is made public. I did not do this by default, since its standard is not directly specified in platform documentation. But then, if there is a platform update and new methods will appear - a publicly available `Request()` function can help out with their support.
I struggle between accessibility and compliance with the word documentation.

**Comment by Daniel-M** [comment]
@toby3d It is implied then that the current platform does not require a public `Request()`. Why would you bother? I don't see the need of the change.
